---
title: figotland
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    authors: 
    guest_authors: 
    image: 
    image_caption: 
- scope:
    path: ''
    type: events
  values:
    permalink: "/kalender/:title/"
    layout: event
    starts_at: 
    ends_at: 
    location: 
    accessibility:
      has_wheelchair: 
      has_toilet: 
      has_audio: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    layout: page
    image: 
    role: 
permalink: pretty
sass:
  sass_dir: styles/
  style: compressed
